#!/usr/bin/env python3
"""Create Dataverse alternate keys for cross-solution upsert patterns.

Defines alternate keys on Compliance Dashboard tables that enable atomic
upserts by business key instead of GUID. This eliminates the non-atomic
``ListRecords -> if-exists -> Create/Update`` race condition documented
in ``docs/troubleshooting.md``.

Alternate Keys Defined:
  - ``fsi_controlassessment``:  ``fsi_controlmasterid`` + ``fsi_assessmentdate`` + ``fsi_zone``
    Enables: ``PATCH /fsi_controlassessments(fsi_controlmasterid=<guid>,fsi_assessmentdate=<date>,fsi_zone=<int>)``

Running with ``--output-docs`` writes the alternate key documentation
to ``docs/alternate-keys.md`` (no Dataverse connection required).
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

PUBLISHER_PREFIX = "fsi"

# ---------------------------------------------------------------------------
# Alternate Key Definitions
# ---------------------------------------------------------------------------

ALTERNATE_KEYS: list[dict] = [
    {
        "table_logical": "fsi_controlassessment",
        "table_display": "Control Assessment",
        "key_schema_name": "fsi_AssessmentUpsertKey",
        "key_display": "Assessment Upsert Key",
        "key_logical": "fsi_assessmentupsertkey",
        "description": (
            "Enables atomic upsert of control assessments by business key "
            "(control + date + zone) instead of GUID. Eliminates the "
            "non-atomic list-then-create race condition in "
            "CD-SolutionFeedCollector and Sync-SolutionAssessments.ps1."
        ),
        "columns": [
            {
                "SchemaName": "fsi_ControlMasterId",
                "LogicalName": "fsi_controlmasterid",
                "Type": "Lookup",
                "Description": "Reference to the control being assessed",
            },
            {
                "SchemaName": "fsi_AssessmentDate",
                "LogicalName": "fsi_assessmentdate",
                "Type": "DateTime",
                "Description": "Date of assessment (deduplication boundary)",
            },
            {
                "SchemaName": "fsi_Zone",
                "LogicalName": "fsi_zone",
                "Type": "Choice",
                "Description": "Governance zone (1/2/3)",
            },
        ],
        "upsert_example": {
            "method": "PATCH",
            "url": (
                "/api/data/v9.2/fsi_controlassessments"
                "(fsi_controlmasterid=<control-guid>,"
                "fsi_assessmentdate=2026-05-12,"
                "fsi_zone=1)"
            ),
            "body": {
                "fsi_status": 1,
                "fsi_score": 100,
                "fsi_notes": "Automated assessment from ACV feed",
            },
        },
    },
]


# ---------------------------------------------------------------------------
# Documentation Generator
# ---------------------------------------------------------------------------


def generate_docs(output_path: str) -> None:
    """Generate alternate key documentation as Markdown.

    Args:
        output_path: Filesystem path for the generated Markdown file.
    """
    lines: list[str] = [
        "# Dataverse Alternate Keys — Cross-Solution Integration",
        "",
        "<!-- Auto-generated by create_csi_alternate_keys.py --output-docs -->",
        "<!-- Do not edit manually — regenerate with: -->",
        "<!-- python scripts/create_csi_alternate_keys.py --output-docs -->",
        "",
        "## Overview",
        "",
        "Alternate keys enable atomic upsert operations by business key instead",
        "of GUID. This eliminates race conditions in the non-atomic",
        "`ListRecords → if-exists → Create/Update` pattern used by",
        "`CD-SolutionFeedCollector` and `Sync-SolutionAssessments.ps1`.",
        "",
        "## Alternate Key Definitions",
        "",
    ]

    for key_def in ALTERNATE_KEYS:
        lines.extend([
            f"### {key_def['key_display']} (`{key_def['key_schema_name']}`)",
            "",
            f"**Table:** `{key_def['table_logical']}` ({key_def['table_display']})  ",
            f"**Logical Name:** `{key_def['key_logical']}`  ",
            f"**Description:** {key_def['description']}",
            "",
            "#### Key Columns",
            "",
            "| SchemaName | Logical Name | Type | Description |",
            "|-----------|-------------|------|-------------|",
        ])
        for col in key_def["columns"]:
            lines.append(
                f"| {col['SchemaName']} | {col['LogicalName']} "
                f"| {col['Type']} | {col['Description']} |"
            )

        example = key_def.get("upsert_example")
        if example:
            lines.extend([
                "",
                "#### Upsert Example",
                "",
                "```http",
                f"{example['method']} {example['url']}",
                "Content-Type: application/json",
                "",
                "{",
            ])
            import json
            body_lines = json.dumps(example["body"], indent=2).split("\n")
            for bl in body_lines[1:-1]:  # skip outer braces
                lines.append(f"  {bl.strip()}")
            lines.extend([
                "}",
                "```",
                "",
                "Dataverse will create a new record if the key combination does",
                "not exist, or update the existing record if it does — atomically.",
                "",
            ])

    lines.extend([
        "## Migration Path",
        "",
        "1. Deploy alternate key using `create_csi_alternate_keys.py`",
        "2. Wait for Dataverse to index the key (may take minutes for large tables)",
        "3. Update `CD-SolutionFeedCollector` flow to use `PATCH` with key URL",
        "   instead of `ListRecords → Create/Update`",
        "4. Update `Sync-SolutionAssessments.ps1` to use `-UpsertByAlternateKey`",
        "",
        "---",
        "",
        "*Auto-generated from create_csi_alternate_keys.py definitions.*",
        "",
    ])

    output_dir = os.path.dirname(output_path)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"  Alternate key documentation written to: {output_path}")


# ---------------------------------------------------------------------------
# Deployment (stub — requires Dataverse connection module)
# ---------------------------------------------------------------------------


def deploy_alternate_keys(
    environment_url: str,
    tenant_id: str,
    dry_run: bool = False,
) -> None:
    """Deploy alternate keys to Dataverse.

    Uses the Dataverse Web API EntityKeyMetadata endpoint.

    Args:
        environment_url: Dataverse environment URL.
        tenant_id: Microsoft Entra tenant ID.
        dry_run: If True, print what would be created without making changes.
    """
    print("Cross-Solution Integration — Alternate Key Deployment")
    print("=" * 55)
    if dry_run:
        print("\n*** DRY RUN — No changes will be made ***\n")

    for key_def in ALTERNATE_KEYS:
        key_columns = [c["LogicalName"] for c in key_def["columns"]]
        print(f"\n  Table: {key_def['table_logical']}")
        print(f"  Key:   {key_def['key_schema_name']}")
        print(f"  Columns: {', '.join(key_columns)}")

        if not dry_run:
            # Actual deployment would POST to:
            # /api/data/v9.2/EntityDefinitions(LogicalName='{table}')/Keys
            print("  Note: Actual deployment requires a Dataverse client module.")

    print(f"\n  Total alternate keys: {len(ALTERNATE_KEYS)}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main() -> None:
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        description="Deploy Dataverse alternate keys for cross-solution upsert",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  # Generate documentation only\n"
            "  python create_csi_alternate_keys.py --output-docs\n\n"
            "  # Dry run\n"
            "  python create_csi_alternate_keys.py --dry-run --interactive\n"
        ),
    )
    parser.add_argument(
        "--tenant-id",
        default=os.environ.get("CSI_TENANT_ID"),
        help="Microsoft Entra ID tenant ID",
    )
    parser.add_argument(
        "--environment-url",
        default=os.environ.get("CSI_ENVIRONMENT_URL"),
        help="Dataverse environment URL",
    )
    parser.add_argument(
        "--interactive",
        action="store_true",
        help="Use interactive browser authentication",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be created without making changes",
    )
    parser.add_argument(
        "--output-docs",
        action="store_true",
        help="Generate docs/alternate-keys.md and exit (no connection)",
    )

    args = parser.parse_args()

    if args.output_docs:
        script_dir = Path(__file__).resolve().parent
        docs_path = script_dir.parent / "docs" / "alternate-keys.md"
        generate_docs(str(docs_path))
        print("Documentation generation complete.")
        sys.exit(0)

    if not args.tenant_id:
        print("ERROR: --tenant-id or CSI_TENANT_ID required", file=sys.stderr)
        sys.exit(1)
    if not args.environment_url:
        print("ERROR: --environment-url or CSI_ENVIRONMENT_URL required", file=sys.stderr)
        sys.exit(1)

    deploy_alternate_keys(
        environment_url=args.environment_url,
        tenant_id=args.tenant_id,
        dry_run=args.dry_run,
    )


if __name__ == "__main__":
    main()
